name: WSJ PER Scraper

on:
  schedule:
    - cron: '0 20 * * 6'  # Sunday 6am Sydney

  workflow_dispatch:


jobs:
  run:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4


    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"


    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        playwright install chromium


    - name: Run script
      env:
        google: ${{ secrets.google }}
      run: |
        python per.py
