name: First pmi workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * 1"  # (선택) 매주 월요일 자동 실행

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1. repo 코드 가져오기
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python 설치
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3. Playwright + Chromium 설치 (핵심)
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install playwright
          playwright install --with-deps chromium

      # 4. 스크립트 실행
      - name: Run PMI script
        run: python pmi.py
